name: build

on:
  workflow_call:
    inputs:
      deploy:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: joinframework/join-ci:latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: hugo --minify

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: join-www
          path: public/

      - name: Deploy
        env:
          DEPLOY_DEST: ${{ secrets.JOIN_DEPLOY_DEST }}
          DEPLOY_PORT: ${{ secrets.JOIN_DEPLOY_PORT }}
          DEPLOY_KEY: ${{ secrets.JOIN_DEPLOY_KEY }}
          DEPLOY_KNOWN_HOST: ${{ secrets.JOIN_DEPLOY_KNOWN_HOST }}
        run: |
          mkdir -p /root/.ssh
          echo "$DEPLOY_KNOWN_HOST" >> /root/.ssh/known_hosts
          chmod 600 /root/.ssh/known_hosts
          eval $(ssh-agent)
          echo "$DEPLOY_KEY" | ssh-add -
          DEPLOY_HOST=$(echo "$DEPLOY_DEST" | sed 's|:.*||')
          ssh -p "$DEPLOY_PORT" -vvv "$DEPLOY_HOST" echo "connexion ok"
