name: cd

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/build.yml

    permissions:
      contents: read

    secrets:
      JOIN_DEPLOY_KNOWN_HOST: ${{ secrets.JOIN_DEPLOY_KNOWN_HOST }}
      JOIN_DEPLOY_KEY: ${{ secrets.JOIN_DEPLOY_KEY }}
      JOIN_DEPLOY_DEST: ${{ secrets.JOIN_DEPLOY_DEST }}
      JOIN_DEPLOY_PORT: ${{ secrets.JOIN_DEPLOY_PORT }}

    with:
      deploy: true
